### ISSUE TITLE
--error does not respect ignore rules

### ISSUE THREAD

**Issue by deftdawg** [buddy-works/dockerfile-linter#17]
Passing in `--ignore` should exclude those rules from causing the linter to return an `--error` for those rules, it does not... 

See screenshot below, all green, but error code returned because ignored rules contain errors.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/4991612/146059818-37ff36dd-c3fd-4308-80b8-4dd822bd3b69.png">

**Comment by BartoszWrobel591** [comment]
Thank you for report, fixed in version 1.2.2. Now you can pass to -e/--error from which error level it should return error code 1. Passing -e warning should fix your problem.
