### ISSUE TITLE
How to inline-ignore 'ED' (and 'EL'?) codes?

### ISSUE THREAD

**Issue by srcshelton** [buddy-works/dockerfile-linter#5]
I'm getting `ED0004` when linting a Docker Dockerfile file ending with a vi/vim modeline in a comment.

The README suggests both `# lint ignore=ED0004` or `# linter ignore=ED0004` (it's not clear whether both work or one is a typo), but seems to suggest that this doesn't work for `ED` or `EL` rules.  Neither form removes the output in my case.

How can I quell the `ED0004` notice the linter is producing?

**Comment by srcshelton** [comment]
Update: `# lint ignore` doesn't work in a general (`EF`) case, `# linter ignore` does - README.md should be updated.

**Comment by BartoszWrobel591** [comment]
Hi, thank you for reporting typo, about ED0004 you need to use flag -i or create yaml file with ignored rules, when you are using editor specific syntax thats trigger linter.
