### ISSUE TITLE
Escaped double-quotes not being correctly parsed

### ISSUE THREAD

**Issue by srcshelton** [buddy-works/dockerfile-linter#8]
The following `RUN` block:
```
RUN test -s "${PRODHOME}/runprod.sh" && \
    sed -i -e "s|^prodhome=\"/usr/local/prod\"$|prodhome=\"${PRODHOME}\"|" \
        "${PRODHOME}/runprod.sh" && \
    chmod 0755 "${PRODHOME}/runprod.sh" && \
    test -x "${PRODHOME}/runprod.sh"
```
... results in `/SC2140/ Word is of the form "A"B"C" (B indicated). Did you mean "ABC" or "A\"B\"C"?`, which suggests that the escaped quotes on line 2 are being treated as unescaped literals.

**Comment by BartoszWrobel591** [comment]
I can't recreate this one, variable PRODHOME have set some default value in ENV or ARG ?

**Comment by srcshelton** [comment]
Good question: it's a multi-stage build with `ARG PRODHOME="/opt/prod"` in the initial global section, and then:

```
ARG PRODHOME
ENV PRODHOME="${PRODHOME}"
```

... in the second stage.

**Comment by srcshelton** [comment]
I've just updated to the latest `1.1.1` release and I'm not seeing this problem any longer myself, either!
